let queries = [
    {id:1, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:2, cat :'meme', title:'nameOfWebsite', url:'url', description:"description"},
    {id:3, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:4, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:5, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:6, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:7, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:8, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:9, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:10, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:11, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:12, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:13, cat :'cat', title:'apples are good', url:'url', description:"description"},
    {id:14, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:15, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:16, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:17, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:18, cat :'meme', title:'nameOfWebsite', url:'url', description:"description"},
    {id:19, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:20, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:21, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:22, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:23, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:24, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:25, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:26, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:27, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:28, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:29, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"},
    {id:30, cat :'cat', title:'nameOfWebsite', url:'url', description:"description"}
]

module.exports = queries