let queries = [
    {id:1, category :'meme', title:'nameOfWebsite', url:'url', description:"description"},
    {id:2, category :'meme', title:'nameOfWebsite', url:'url', description:"description"},
    {id:3, category :'meme', title:'nameOfWebsite', url:'url', description:"description"},
    {id:4, category :'meme', title:'nameOfWebsite', url:'url', description:"description"},
    {id:5, category :'meme', title:'nameOfWebsite', url:'url', description:"description"},
    {id:6, category :'meme', title:'nameOfWebsite', url:'url', description:"description"},
    {id:7, category :'meme', title:'nameOfWebsite', url:'url', description:"description"},
    {id:8, category :'meme', title:'nameOfWebsite', url:'url', description:"description"},
    {id:9, category :'meme', title:'nameOfWebsite', url:'url', description:"description"},
    {id:10, category :'meme', title:'nameOfWebsite', url:'url', description:"description"},
    {id:12, category :'food', title:'nameOfWebsite', url:'url', description:"description"},
    {id:11, category :'food', title:'nameOfWebsite', url:'url', description:"description"},
    {id:13, category :'food', title:'apples are good', url:'url', description:'description'},
    {id:14, category :'food', title:'nameOfWebsite', url:'url', description:'description'},
    {id:15, category :'food', title:'nameOfWebsite', url:'url', description:'description'},
    {id:16, category :'food', title:'nameOfWebsite', url:'url', description:'description'},
    {id:17, category :'food', title:'nameOfWebsite', url:'url', description:'description'},
    {id:18, category :'food', title:'nameOfWebsite', url:'url', description:'description'},
    {id:20, category :'food', title:'nameOfWebsite', url:'url', description:'description'},
    {id:19, category :'food', title:'Fruits from A-Z - Half Your Plate', url:'https://www.halfyourplate.ca/fruits-and-veggies/fruits-a-z/', description:'Fruits from A-Z. Browse: Home · Fruit and Veggie Facts; Fruits from A-Z. ACÉROLA (cerise des Antilles). Acerola – West Indian Cherry.'},
    {id:21, category :'social', title:'nameOfWebsite', url:'url', description:'description'},
    {id:22, category :'social', title:'Department of Health and Social Care - GOV.UK', url:'https://www.gov.uk/government/organisations/department-of-health-and-social-care', description:'We support ministers in leading the nation\'s health and social care to help people live more independent, healthier lives for longer. DHSC is a ministerial ...'},
    {id:23, category :'social', title:'Social Enterprise UK | Home', url:'https://www.socialenterprise.org.uk/', description:'The UK body for social enterprise - business with a social or environmental mission. We support business where society profits.'},
    {id:24, category :'social', title:'Social | Definition of Social by Merriam-Webster', url:'https://www.merriam-webster.com/dictionary/social', description:'social · 1 : relating to or involving activities in which people spend time talking to each other or doing enjoyable things with each other She has poor/good ...'},
    {id:25, category :'social', title:'Why we may have to re-learn to socialise - BBC Worklife', url:'https://www.bbc.com/worklife/article/20210218-why-we-may-have-to-re-learn-to-socialise', description:'18 Feb 2021 — With socialising at a near halt during the pandemic, our social muscles have atrophied. We may have to re-train ourselves to be with other'},    {id:26, category :'social', title:'Impact of the COVID-19 pandemic on social media - Wikipedia', url:'https://en.wikipedia.org/wiki/Impact_of_the_COVID-19_pandemic_on_social_media', description:"During a time of social distance and limited contact with others, social media became an important place to interact. Social media platforms are meant to ..."},
    {id:27, category :'social', title:'Social media - Wikipedia', url:'https://en.wikipedia.org/wiki/Social_media', description:'Some of the most popular social media websites, with over 100 million registered users, include Facebook (and its associated Facebook Messenger), TikTok, WeChat ...'},
    {id:28, category :'social', title:'The Top 10 Social Media Sites & Platforms 2021', url:'https://www.searchenginejournal.com/social-media/biggest-social-media-sites/', description:'22 Jun 2021 — The Top 10 Social Media Sites and Platforms · 1. Facebook · 2. YouTube · 3. WhatsApp · 4. Instagram · 5. TikTok · 6. Snapchat · 7. Reddit · 8. Pinterest.'},
    {id:29, category :'social', title:'9 Types of Social Media and How Each Can Benefit Your Business', url:'https://blog.hootsuite.com/types-of-social-media/', description:'2 Sept 2021 — One thing that\'s changed since the early days of social media is that many platforms used to focus on one function, such as social networking or ...'},
    {id:30, category :'social', title:'What is Social Media? - WhatIs.com', url:'https://whatis.techtarget.com/definition/social-media', description:'Social media is a collective term for websites and applications that focus on communication, community-based input, interaction, content-sharing and collaboration. ... Some popular examples of general social media platforms include Twitter, Facebook and LinkedIn.'}
]

module.exports = queries
